/**
 * Generate GraphQL test SDK fixtures with `runtime: "external"` so they import
 * the shared wrapper module (traps / class identity work in tests).
 *
 * Usage:
 *   bun scripts/generate-test-sdks.ts
 *   bun scripts/generate-test-sdks.ts --only=books
 *   bun scripts/generate-test-sdks.ts --check
 *   bun scripts/generate-test-sdks.ts --refresh-spacex  # re-introspect SpaceX schema
 */
import {
    buildClientSchema,
    buildSchema,
    getIntrospectionQuery,
    printSchema,
    type GraphQLSchema,
    type IntrospectionQuery,
} from "graphql";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Generator } from "../src/graphql/builder/generator";
import { GeneratorSelectionTypeFlavorDefault } from "../src/graphql/flavors/default/generator-flavor";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MAKE_ROOT = path.resolve(__dirname, "..");
const TESTS_ROOT = path.join(
    MAKE_ROOT,
    "src/graphql/flavors/default/__tests__",
);

type Fixture = {
    id: string;
    /** Relative to __tests__/ */
    schemaPath: string;
    /** Relative to __tests__/ */
    outPath: string;
    authHeaderName?: string;
    /**
     * If set, schema can be refreshed from live introspection
     * (`--refresh-spacex` or `--refresh-all-remote`).
     */
    introspectionUrl?: string;
};

/** Catalog of fixtures to generate for GraphQL flavor tests. */
export const graphqlTestFixtures: Fixture[] = [
    {
        id: "books",
        schemaPath: "schemas/books.graphql",
        outPath: "examples/books.generated.ts",
    },
    {
        id: "dates",
        schemaPath: "schemas/dates.graphql",
        outPath: "examples/dates.generated.ts",
    },
    {
        id: "unions",
        schemaPath: "schemas/unions.graphql",
        outPath: "examples/unions.generated.ts",
    },
    {
        id: "directives",
        schemaPath: "schemas/directives.graphql",
        outPath: "examples/directives.generated.ts",
    },
    {
        id: "contentful",
        schemaPath: "schemas/contentful.graphql",
        outPath: "examples/contentful.generated.ts",
        authHeaderName: "Authorization",
    },
    {
        id: "spacex",
        schemaPath: "schemas/spacex.graphql",
        outPath: "examples/spacex.generated.ts",
        introspectionUrl: "https://spacex-production.up.railway.app/graphql",
    },
];

const WRAPPER_MODULE = "@/graphql/flavors/default/wrapper";

const HEADER = `// @generated by packages/make/scripts/generate-test-sdks.ts — do not edit by hand
// runtime: external (imports SelectionWrapper / RootOperation from shared wrapper module)
`;

async function introspectToSdl(url: string): Promise<string> {
    const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: getIntrospectionQuery() }),
    });
    if (!res.ok) {
        throw new Error(`Introspection failed ${url}: HTTP ${res.status} ${await res.text()}`);
    }
    const json = (await res.json()) as {
        data?: IntrospectionQuery;
        errors?: unknown;
    };
    if (json.errors || !json.data) {
        throw new Error(
            `Introspection failed ${url}: ${JSON.stringify(json.errors ?? "no data")}`,
        );
    }
    const schema = buildClientSchema(json.data);
    return printSchema(schema);
}

async function loadSchema(fixture: Fixture): Promise<GraphQLSchema> {
    const schemaAbs = path.join(TESTS_ROOT, fixture.schemaPath);
    const sdl = await readFile(schemaAbs, "utf8");
    return buildSchema(sdl);
}

async function generateFixture(fixture: Fixture): Promise<string> {
    const schema = await loadSchema(fixture);

    const generator = new Generator(GeneratorSelectionTypeFlavorDefault);
    const code = await generator.generate({
        schema,
        options: {},
        authConfig: fixture.authHeaderName
            ? { headerName: fixture.authHeaderName }
            : undefined,
        runtime: "external",
        externalRuntime: {
            wrapperModule: WRAPPER_MODULE,
        },
    });

    return `${HEADER}// fixture: ${fixture.id}\n${code}\n`;
}

async function refreshRemoteSchemas(fixtures: Fixture[]) {
    for (const fixture of fixtures) {
        if (!fixture.introspectionUrl) continue;
        console.log(`[introspect] ${fixture.id} ← ${fixture.introspectionUrl}`);
        const sdl = await introspectToSdl(fixture.introspectionUrl);
        const schemaAbs = path.join(TESTS_ROOT, fixture.schemaPath);
        await mkdir(path.dirname(schemaAbs), { recursive: true });
        const body =
            `# Introspected from ${fixture.introspectionUrl}\n` +
            `# Refreshed by generate-test-sdks.ts — commit when intentionally updating\n\n` +
            sdl;
        await writeFile(schemaAbs, body, "utf8");
        console.log(`[wrote] ${fixture.schemaPath}`);
    }
}

async function main() {
    const args = process.argv.slice(2);
    const check = args.includes("--check");
    const refreshAllRemote = args.includes("--refresh-all-remote");
    const refreshSpacex = args.includes("--refresh-spacex");
    const onlyArg = args.find((a) => a.startsWith("--only="));
    const only = onlyArg?.slice("--only=".length);

    let fixtures = only
        ? graphqlTestFixtures.filter((f) => f.id === only)
        : graphqlTestFixtures;

    if (fixtures.length === 0) {
        console.error(`No fixtures matched${only ? ` --only=${only}` : ""}`);
        process.exit(1);
    }

    if (refreshSpacex || refreshAllRemote) {
        const remote = refreshAllRemote
            ? fixtures.filter((f) => f.introspectionUrl)
            : fixtures.filter((f) => f.id === "spacex" && f.introspectionUrl);
        await refreshRemoteSchemas(remote);
    }

    let dirty = false;

    for (const fixture of fixtures) {
        const outAbs = path.join(TESTS_ROOT, fixture.outPath);
        const next = await generateFixture(fixture);

        if (check) {
            let prev = "";
            try {
                prev = await readFile(outAbs, "utf8");
            } catch {
                prev = "";
            }
            if (prev !== next) {
                console.error(`[dirty] ${fixture.outPath}`);
                dirty = true;
            } else {
                console.log(`[ok] ${fixture.outPath}`);
            }
        } else {
            await mkdir(path.dirname(outAbs), { recursive: true });
            await writeFile(outAbs, next, "utf8");
            console.log(`[wrote] ${fixture.outPath}`);
        }
    }

    if (check && dirty) {
        console.error(
            "\nTest SDKs are out of date. Run: bun scripts/generate-test-sdks.ts",
        );
        process.exit(1);
    }
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
