/**
 * Generate GraphQL test SDK fixtures with `runtime: "external"` so they import
 * the shared wrapper module (traps / class identity work in tests).
 *
 * Usage:
 *   bun scripts/generate-test-sdks.ts
 *   bun scripts/generate-test-sdks.ts --only=books
 *   bun scripts/generate-test-sdks.ts --check
 */
import { buildSchema } from "graphql";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Generator } from "../src/graphql/builder/generator";
import { GeneratorSelectionTypeFlavorDefault } from "../src/graphql/flavors/default/generator-flavor";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MAKE_ROOT = path.resolve(__dirname, "..");
const TESTS_ROOT = path.join(
    MAKE_ROOT,
    "src/graphql/flavors/default/__tests__",
);

type Fixture = {
    id: string;
    schemaPath: string;
    outPath: string;
    authHeaderName?: string;
};

/** Catalog of fixtures to generate for GraphQL flavor tests. */
export const graphqlTestFixtures: Fixture[] = [
    {
        id: "books",
        schemaPath: "schemas/books.graphql",
        outPath: "examples/books.generated.ts",
    },
    {
        id: "dates",
        schemaPath: "schemas/dates.graphql",
        outPath: "examples/dates.generated.ts",
    },
];

const WRAPPER_MODULE = "@/graphql/flavors/default/wrapper";

const HEADER = `// @generated by packages/make/scripts/generate-test-sdks.ts — do not edit by hand
// runtime: external (imports SelectionWrapper / RootOperation from shared wrapper module)
`;

async function generateFixture(fixture: Fixture): Promise<string> {
    const schemaAbs = path.join(TESTS_ROOT, fixture.schemaPath);
    const sdl = await readFile(schemaAbs, "utf8");
    const schema = buildSchema(sdl);

    const generator = new Generator(GeneratorSelectionTypeFlavorDefault);
    const code = await generator.generate({
        schema,
        options: {},
        authConfig: fixture.authHeaderName
            ? { headerName: fixture.authHeaderName }
            : undefined,
        runtime: "external",
        externalRuntime: {
            wrapperModule: WRAPPER_MODULE,
        },
    });

    return `${HEADER}// fixture: ${fixture.id}\n${code}\n`;
}

async function main() {
    const args = process.argv.slice(2);
    const check = args.includes("--check");
    const onlyArg = args.find((a) => a.startsWith("--only="));
    const only = onlyArg?.slice("--only=".length);

    const fixtures = only
        ? graphqlTestFixtures.filter((f) => f.id === only)
        : graphqlTestFixtures;

    if (fixtures.length === 0) {
        console.error(`No fixtures matched${only ? ` --only=${only}` : ""}`);
        process.exit(1);
    }

    let dirty = false;

    for (const fixture of fixtures) {
        const outAbs = path.join(TESTS_ROOT, fixture.outPath);
        const next = await generateFixture(fixture);

        if (check) {
            let prev = "";
            try {
                prev = await readFile(outAbs, "utf8");
            } catch {
                prev = "";
            }
            if (prev !== next) {
                console.error(`[dirty] ${fixture.outPath}`);
                dirty = true;
            } else {
                console.log(`[ok] ${fixture.outPath}`);
            }
        } else {
            await mkdir(path.dirname(outAbs), { recursive: true });
            await writeFile(outAbs, next, "utf8");
            console.log(`[wrote] ${fixture.outPath}`);
        }
    }

    if (check && dirty) {
        console.error(
            "\nTest SDKs are out of date. Run: bun scripts/generate-test-sdks.ts",
        );
        process.exit(1);
    }
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
